### ISSUE TITLE
Howto make MySQL accessible from Hostsystem?

### ISSUE THREAD

**Issue by ThomasLohner** [marmaladeDE/Development-VM#1]
Currently bind-address = 127.0.0.1 is configured via Puppet in /etc/mysql/my.cnf

How can i change this? We need to connect to MySQL from the Host-OS for example to be able to use HeidiSQL.

**Comment by kyoya-de** [comment]
Hi Thomas,

the binding setting should be removed with Augeas, but it seems that it won't work. :(
We'll fix that soon.

Greetz Stefan

Am 01.09.2015 um 14:43 schrieb Thomas Lohner:

**Comment by ThomasLohner** [comment]
Ich glaube ich weiß warum das passiert:

modules/vmsetup/manifests/init.pp:

```
  class { "mysql::server":
    require => Exec["apt_update"]
  }

  class { "mysql::client":
    require => Exec["apt_update"]
  }

  augeas { "set mysql bind-address":
    changes => [
      "set /files/etc/mysql/my.cnf/target[3]/bind-address 0.0.0.0"
    ],
    require  => [
      Package['mysql-server']
    ],
    notify => Service['mysql']
  }
```

Ihr setzt bind-address via augeas, was dann aber wiederum von mysql::server: überschrieben wird, denn mysql::server hat als Defaultwert für bind_address 127.0.0.1 (siehe $default_options in modules/mysql/manifests/params.pp)

Der korrekte Weg das zu setzen ist:

```
$override_options = {
  'mysqld' => {
    'bind-address' => $bindaddress,
  }
}

class { '::mysql::server':
  override_options        => $override_options
}
```

Bei der Gelegenheit wär es natürlich noch schöner, wenn ihr die gesamte MySQL Logik in eine eigene Klasse auslagert, so wie bei apache, elastic, php usw. auch schon ;-)

**Comment by kyoya-de** [comment]
Fixed with commit [8ca3ddeef75118cf793b7ccbcaaff8b63bc758d8](https://github.com/marmaladeDE/Development-VM/commit/8ca3ddeef75118cf793b7ccbcaaff8b63bc758d8).
