### ISSUE TITLE
opcache not installed correctly

### ISSUE THREAD

**Issue by ThomasLohner** [marmaladeDE/Development-VM#2]
Opcache doesn't work even if enabled in config because of:

```
$ cat /etc/php5/mods-available/opcache.ini 
zend_extension==
opcache.enable=1
opcache.cli_enable=1
```

There's something wrong with the template or param name.

**Comment by kyoya-de** [comment]
Fixed with commit #[09493b8d3895aed9ce9cda127d5c25cd746f8c5f](https://github.com/marmaladeDE/Development-VM/commit/09493b8d3895aed9ce9cda127d5c25cd746f8c5f).
